services:
  - type: web
    name: monblog
    runtime: docker
    plan: free
    buildCommand: |
      composer install
      php artisan key:generate
      npm install
      npm run build
      php artisan storage:link
    startCommand: php artisan serve --host=0.0.0.0 --port=10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: database/database.sqlite
